export const THEMES = [
    "11e art",
    "amour",
    "anthologie",
    "arc-en-ciel",
    "ascension",
    "avant-après",
    "bataille d'oum tounsi",
    "bleu-vert",
    "bonheur",
    "calendrier",
    "communauté",
    "composition",
    "coutures",
    "cuisine",
    "déménagement",
    "dinosaures",
    "district minier",
    "équipe",
    "espoir",
    "famille",
    "fantasme",
    "flamme",
    "glace",
    "handicap",
    "harcèlement",
    "IA",
    "illusion",
    "intrigue",
    "jeu",
    "JO",
    "joyaux",
    "lumière",
    "mal à l'aise",
    "montagne",
    "moulin à vent",
    "mur/barrière",
    "musée",
    "mystère/détective",
    "nature sauvage",
    "œuf",
    "organe",
    "panache",
    "point de fuite",
    "politique",
    "pyjama",
    "pyramide",
    "renaissance",
    "respiration",
    "ressources ",
    "retraite",
    "rêves",
    "rouage",
    "route",
    "satire",
    "sécurité",
    "serenyssime",
    "solarpunk",
    "sommeil",
    "soupir",
    "sports d'hiver",
    "télécommunications",
    "trains",
    "utopie",
    "venu d'ailleurs",
    "voyage",
]